# Generated by Django 3.0.5 on 2020-10-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(default=False, help_text='Does the squirrel have approaches?'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(default=False, help_text='Is the squirrel chasing?'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Climbing',
            field=models.BooleanField(default=False, help_text='Is the squirrel climbing?'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(default=None, help_text='Date of record'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Eating',
            field=models.BooleanField(default=False, help_text='Is the squirrel eating?'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(default=False, help_text='Is the squirrel foraging?'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(default=False, help_text='Is the squirrel indifferent?'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(default=False, help_text='Does the squirrel have kuks?'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], default='Ground Plane', help_text='Location of squirrel', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(default=False, help_text='Does the squirrel have moans?'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Other_Activity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], default='Gray', help_text='Primary fur color of squirrel', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(default=False, help_text='Does the squirrel have quaas?'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(default=False, help_text='Is the squirrel running?'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Runs_From',
            field=models.BooleanField(default=False, help_text='Does the squirrel run from?'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], default='AM', help_text='Shift of squirrel', max_length=2),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Specific_Location',
            field=models.CharField(blank=True, default=None, help_text='Specific location of squirrel', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Tail_Flags',
            field=models.BooleanField(default=False, help_text='Does the squirrel have tail flags?'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Tail_Twitches',
            field=models.BooleanField(default=False, help_text='Does the squirrel have tail twitches?'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(default=None, help_text='Unique ID of squirrel', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='X_Latitude',
            field=models.FloatField(default=None, help_text='X-Latitude of Squirrel'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Y_Longitude',
            field=models.FloatField(default=None, help_text='Y-Longitude of Squirrel'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default='Adult', help_text='Age of squirrel', max_length=15, null=True),
        ),
    ]
