# Generated by Django 3.0.5 on 2020-10-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201014_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='age',
            new_name='Age',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Specific_Location',
        ),
    ]
