# Generated by Django 3.0.5 on 2020-10-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201017_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(default=None, help_text='Unique ID of squirrel', max_length=100, primary_key=True, serialize=False),
        ),
    ]
