# Generated by Django 3.0.5 on 2020-10-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201020_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Other_Activity',
            field=models.TextField(blank=True, help_text='Other activities?'),
        ),
    ]
